function V=haarfeature(img)
Nofeature=0;
V=zeros(1,... nb de features ...);
% feature horizontale 1
% pour toutes les largeurs possibles
for i=1:...
    % pour toutes les épaisseurs possibles
    for j=1:...
        % pour toutes les positions en ligne
        for x=1:...
            % pour toutes les positions en colonnes
            for y=1:...
                Nofeature=Nofeature+1;
                V(Nofeature)=...;
            end
        end
    end
end

% feature verticale
...
...
...
...
...
...

% feature horizontale 2
...
...
...
...
...
...